### ISSUE TITLE
White-Beet-EI strange problem regarding Session Setup Request

### ISSUE THREAD

**Issue by IonelFratila** [Sevenstax/FreeV2G#14]
I have a strange problem related to White-Beet-EI module, not the FreeV2G software, but the guys from CODICO advised me to put this issue here.
I'm using a WB-EI module which I updated to V01_01_02 version to interface the CCS EV with a host controller for which I'm developing the firmware.
I have started by sending the commands for initialization and start of the CP, SLAC and V2G services (the others do not seem to be useful for running the EV charging process). When connecting the EV, all the messages seemed to be transmitted as in the user manual (with some minor differences, but the message sequence was OK), I was receiving the SLAC successful message (ModID=0x28, SubID=0x80) and then the V2G Session Started message (ModID=0x27, SubID=0x80), followed by the request for EVSE ID with Format=1 (ModID=0x27, SubID=0x82). 
-Here I tried several times to find the correct format for EVSE ID, because the information in the manual and even in IEC 15118 / DIN SPEC 70121 or DIN SPEC 91286 is very brief and unclear, in my opinion. At the Set EVSE ID command (ModID=0x27, SubID=0x68) I always received the result code = 0x04 and unfortunately I could not test this command except by resuming the connection with the car each time, otherwise WB does not accept the command (result code 0x05). Each time, the communication with the car was interrupted after the Session Setup Response message (Failed).
-At one point during these tests, for no apparent reason, I started not to receive the EVSE ID Request message (ModID=0x27, SubID=0x82) from the WB module. Now I’m receiving each time Session Stopped message (ModID=0x27, SubID=0x81) directly after Session Started (ModID=0x27, SubID=0x80). Between these two messages I only receive some messages with type 0x86DD (IPv6 messages). I wonder if it is normal for WB to send these messages to the Host controller. On the CCS analyzer I can see that EV is sending the Session Setup Request message with Session ID other than 0 (I think it is the same value all the time), which is contrary to the standard CEI15118 / DIN SPEC 70121 - the EV has just been connected. Moreover, from this moment on, WB module no longer communicates with the host controller, nor does it even send CP status change messages when the EV is disconnected, only after the Power-On reset. That's why I suspect that WB sends certain information to the EV, which causes it to send a session ID other than 0 in the Session Setup Request message.
I’m using for test one Skoda CitiGo, but this behavior of the WB module is the same also with another car. With both cars, charging starts normally at another charging station.
Please tell me if you have any idea regarding this strange behavior and if the WB module configuration can somehow be reset to default initial values.
Thank You.

**Comment by IonelFratila** [comment]
Hello guys,
Do you have an answer to the questions above?
Thank You.

**Comment by jpo-stx** [comment]
Hello @IonelFratila ,

1. You can only issue the "Set EVSE ID" command when the EVSE requested it. 
   - The correct module ID for the V2G service is 0x27. You are right the examples are wrong. This will be fixed in the upcoming version of the manual.
   - Have you checked the application examples in chapter **19.8 V2G Charging Session Example**
   - Timings are handled in the whitebeet module itself, but the host needs to answer to responses in specific timeouts, hence the timeout value is sent in the messages. When the host doesn't answer within the timeout window the connection to the EV will be closed.
   - Regarding SLAC, can you point me to the reference in specification where this is stated. From what I have read in the IEC specification the matching is started after the EVSE set the duty cycle to 5%.

2. I cannot say exactly when the next firmware version will be available, but it should be released in the next two weeks. The whitebeet module itself does not save the configuration and therefore it should alwasy be in it's original state after a power cycle. It should work with an EV that sends a zero Session ID in SessionSetupReq message.

3. On this one I am still checking with a colleague.

4. Payload is 3 bytes. The description is missing the type after the Code:
| Type | uint8 | The type of the requested charge loop parameters. 0: DC, 1: AC |

BR
Jan

**Comment by IonelFratila** [comment]
Hi Jan,
Thank you for your answers. These are very helpful for me to understand how to communicate with WB module, especially regarding when the commands must be sent and in what sequence. regarding the estimated term of 2 weeks, it doesn't seem so discouraging. I look forward to the new SW version.

1. Regarding the start of the SLAC Service, there are statements in DIN SPEC 70121:2014 (similar requirements in ISO 15118) like:
"8.3.3.3.2.MME Content for SLAC
...
[V2G-DC-574] The EVSE shall generate a random NMK after Power-On and after every lug-out of an EV, and it shall use this random NMK for setting up a logical network.
NOTE: NMK and NID should be generated after plug-out instead of plug-in to save time for Data-Link setup.
...
8.3.5.5.2.Requirements on EVSE side
[V2G-DC-603] The EVSE shall configure its Green PHY node to the NID and NMK values sent in CM_SLAC_MATCH.CNF at the latest after sending the CM_SLAC_MATCH.CNF. The configuration can also be done at any time before (e.g. when unplugging of previous EV). The configuration shall be done by sending a CM_SET_KEY.REQ."

From these requirements it is obvious that the SLAC Service must be started/restarted right after Power-On or plug-out. But is not so obvious when V2G Service must be started. Please tell me if it is OK if I start the V2G Service also after Power-On or plug-out, right after starting SLAC Service, or it should be started only after receiving the message SLAC Matching Process successful (as in FreeV2G application log). 

2. Because I want to continue my development with the WB modules I have, I have to ask you again if you have any idea what makes EV transmit Session ID other than 0 after the plug-in and how can I convince it to transmit again Session ID=0  in SessionSetupReq message. Again, it is not related to EV, which works properly on other stations, but something in communication with WB makes it react that way.

Thank You,
Ionel

**Comment by klth** [comment]
Hello @IonelFratila ,

We have the same issue with our test car (session id != 0). To continue with your implementation you can try to limit the WB to the DIN 70121 protocol. If I remember right this works for our VW eUp as a workaround.

best regards 
Klaus

**Comment by ttu-stx** [comment]
>     1. Because I want to continue my development with the WB modules I have, I have to ask you again if you have any idea what makes EV transmit Session ID other than 0 after the plug-in and how can I convince it to transmit again Session ID=0  in SessionSetupReq message. Again, it is not related to EV, which works properly on other stations, but something in communication with WB makes it react that way.

Have you seen Jan's reply on this? A new sw version which will most probably released within next week will fix this issue.

**Comment by jpo-stx** [comment]
> 
> 
> Hi Jan, Thank you for your answers. These are very helpful for me to understand how to communicate with WB module, especially regarding when the commands must be sent and in what sequence. regarding the estimated term of 2 weeks, it doesn't seem so discouraging. I look forward to the new SW version.

Good to hear that this timeframe fits yours.

> 
>     1. Regarding the start of the SLAC Service, there are statements in DIN SPEC 70121:2014 (similar requirements in ISO 15118) like:
>        "8.3.3.3.2.MME Content for SLAC
>        ...
>        [V2G-DC-574] The EVSE shall generate a random NMK after Power-On and after every lug-out of an EV, and it shall use this random NMK for setting up a logical network.
>        NOTE: NMK and NID should be generated after plug-out instead of plug-in to save time for Data-Link setup.
>        ...
>        8.3.5.5.2.Requirements on EVSE side
>        [V2G-DC-603] The EVSE shall configure its Green PHY node to the NID and NMK values sent in CM_SLAC_MATCH.CNF at the latest after sending the CM_SLAC_MATCH.CNF. The configuration can also be done at any time before (e.g. when unplugging of previous EV). The configuration shall be done by sending a CM_SET_KEY.REQ."
> 
> 
> From these requirements it is obvious that the SLAC Service must be started/restarted right after Power-On or plug-out. But is not so obvious when V2G Service must be started. Please tell me if it is OK if I start the V2G Service also after Power-On or plug-out, right after starting SLAC Service, or it should be started only after receiving the message SLAC Matching Process successful (as in FreeV2G application log).
> 

Starting the service in the beginning should be OK, because the service waits for a valid IP configuration, which is available after SLAC success.. I will check this next week.

>     1. Because I want to continue my development with the WB modules I have, I have to ask you again if you have any idea what makes EV transmit Session ID other than 0 after the plug-in and how can I convince it to transmit again Session ID=0  in SessionSetupReq message. Again, it is not related to EV, which works properly on other stations, but something in communication with WB makes it react that way.
> 
> 
> Thank You, Ionel

It is clear that the EV is not according to spec. An old session ID is only allowed to be sent when a session was paused, But a session resume is only possible if there was not plug-out in between. Unfortunatly I don't see any possibility besides trying to set the session ID to zero on EV side :(

**Comment by zacharyalutz** [comment]
I have had a similar experience with V2G message sequencing between SessionSetup and ChargeParameterDiscovery. After the "Request EVSEID" from whitebeet, I have had to add ~333ms delay and even then Whitebeet requires at least one retry to accept EVSEID. After this point, I would expect a "Request Authorization Status" but the next message from whitebeet is "Request Schedules" followed by "Request Discovery Charge Parameters"... 

I am testing on an EV emulator platform from Keysight, and the log shows an "AuthorizationReq" from emulator and "AuthorizationRes" from EVSE with "ResponseCode=OK" and "EVSEProcessing=Finished". This is strange since I never actually received the request from Whitebeet. There is no evidence of the "Request Authorization Status" message in wireshark logs. I suspected that maybe the host platform was faster than wireshark could manage and missed the frame, so I  setup a logic analyzer to trigger on receipt of that message: still no authorization request.

I have run this test several times with the same results. I have pattern-matched the exact host messages from the FreeV2G application to have a common reference point, but the problem persists. The only remaining difference at this point between my PC running the FreeV2G app as host versus my real host platform is latency. I have developed the host interface on an FPGA, which is much much faster than the PC. This disparity is what caused me to inject delay. Can you provide timing requirements for the Whitebeet-EI? Can you discern any missteps my side? Can you provide any more insight into V2G message sequencing than the documentation provides? 

Below you will find a summary of the problems I have encountered, the software version info as well as wireshark capture and emulator log as visual aids. Any insight you have would be great, thanks for your time!


#### Summary
- Whitebeet sends response code "0x01" to "Set EVSEID" message from host with correctly formatted EVSEID for much longer than seems reasonable.
  - Have to inject delay to get the command to be accepted.
- Whitebeet goes from "Request EVSEID" directly to "Request Schedules" and "Request Discovery Charge Parameters", skipping over "Request Authorization.
- According to the Keysight EV emulator, Whitebeet is sending a valid "AuthorizationRes" message even though the "Request Authorization" message was not bridged over to host interface.
- With respect to the host: how much time should be allowed between receipt of asynchronous request to transmission of response? 


#### SW Info
  ```
  APPLICATION:
    Name:      ISO15118 (EVSE)
    Version:   V01_01_02
    Target:    WHITE-BEET
    CPU:       STM32F745

  PRODUCT VERSION:
   String: SEVENSTAX_LIB_V_10_00_03
   Hex:    0x000a0003
   Dec:    100003

   Hostcontroller Interface: ETHERNET!
  ```

#### Wireshark capture
  [No-AuthSts-Request.pcapng.gz](https://github.com/Sevenstax/FreeV2G/files/7487737/No-AuthSts-Request.pcapng.gz)


#### Emulator Log
  ![image](https://user-images.githubusercontent.com/29818706/140548073-3b483e56-bd58-4f25-a5d9-b119e622c31b.png)

**Comment by jpo-stx** [comment]
Hello @zacharyalutz ,

thanks for the detailed report! Very much appreciated!
I will check on the authorization issue and the timing requirements and come back you as soon as possible.

BR
Jan

**Comment by jpo-stx** [comment]
I have a question regarding the authorization. Can you tell me if you set the payment options, because i do not see the configuration in the wireshark log. This is the message "17.10.5 Set payment options" (0x64). If you did not configure the payment options the authorization is not requested at the host controller.

**Comment by zacharyalutz** [comment]
Yes you were right, the payments options were set incorrectly. This has peeled back the next layer of the onion, so thanks for that! One overarching issue remains, though, which I mentioned in the message above: timing.

> With respect to the host: how much time should be allowed between receipt of asynchronous request to transmission of response? 

I am routinely getting response code 0x01 "Module Busy", which triggers a retry in the host. I have tried to introduce delay, but  am not certain how to "design" the delay interval in the absence of timing requirements. To save you the grief of re-reading my last post, the host platform i am developing is on an FPGA which is extremely fast, as there is no software layer. I am peeling apart the ethernet frames at layer 2 and building response frames in hardware. 

So, for almost every response I send to an asynchronous message from EV, I am having getting 0x01 result code back from Whitebeet. This caused me to add delay between request/response pairs but it seems as though Whitebeet requires more delay to process certain commands than others (e.g. Set EVSEID for some reason takes more time than others). As a result, I am ultimately failing to meet the timeout requirements of ISO 15118 because Whitebeet won't accept my responses in time.

Any insight here would be greatly appreciated. Thanks for your ongoing support!

**Comment by jpo-stx** [comment]
I checked the timing requirements of the whitebeet and it should be ready in ~1-2ms with a maximum of 3ms after it sent the request message to the host.

Please let me know if setting these timings solves the issue.

**Comment by jpo-stx** [comment]
> ...
> From these requirements it is obvious that the SLAC Service must be started/restarted right after Power-On or plug-out. But is not so obvious when V2G Service must be started. Please tell me if it is OK if I start the V2G Service also after Power-On or plug-out, right after starting SLAC Service, or it should be started only after receiving the message SLAC Matching Process successful (as in FreeV2G application log).
> ...

@IonelFratila , you can start the V2G service before doing the SLAC.

**Comment by IonelFratila** [comment]
I corrected the problem with Set EVSEID command. Now is working well. Also, after a few days of testing using another EV (VW eGolf), my Skoda CitiGo decided to send the correct Session ID=0, for no particular reason. I think this issue will need extra attention in the future.
 
Regarding the timing requirements, I have the same problem with the answer to Set Authorization Status command (ModID=0x27, SubID=0x69). My host controller has a typical response to request messages from WB of 2ms, so I have no problem with the EVSEID request. For the Authorization Status Request, I've tried different delays up to 100ms, but the answer to Set Authorization Status is always 0x01 (Module is busy).
Regarding these two commands, I've noticed that EVSEID Request ask for a time-out of 1.544ms and Authorization Status Req ask for a time-out of 60.000ms. It is possible that 100ms delay to be insufficient?
ERx: 123456789ABC C49300215136 6003 0004000C C02783FF0004 [0000EA60]83C1	;Req Authorization Status
ETx: FFFFFFFFFFFF 123456789ABC 6003 00040009 C02769110001 [00]00C1	;Set Authorization Status=0x00
ERx: 123456789ABC C49300215136 6003 00040009 C02769110001 [01]D9C1	;Set Authorization Response with Result=0x01

@zacharyalutz, Please tell me if you solved the problem with Set Authorization Status command.

Thank You,
B.R.
Ionel Fratila

**Comment by jpo-stx** [comment]
Hi @IonelFratila ,

1. I looked into the issue and tested different timings (5ms, 114ms, 1511ms, 4511ms) and I always got the response code OK back from the EVSE. Generally as mentioned in https://github.com/Sevenstax/FreeV2G/issues/14#issuecomment-965499235 the Whitebeet is ready to receive the set command after a maximum of 3ms. Can you send me the complete log of the messages, maybe it is dependent from the configuration.
2. Have you repeated the command after you got the response code 1 (busy)? What happend after that?

BR Jan

**Comment by zacharyalutz** [comment]
@IonelFratila: I am no longer having an issue with the "Set Authorization Status" command per se, but still encounter the "Module Busy" response code `0x01` for multiple other request/response pairs. I have inserted a "wait" state that lasts ~2.62ms between receipt of each asynchronous message and sending a response message back. 

Based on my observations, the "Module Busy" response code from Whitebeet seems to occur when receiving messages on both the vehicle and host interfaces. My solution to this is to retry sending the message after another "wait" state. This seems to work most of the time, but is sensitive to the duration of the subsequent "wait" states. That is, if the delay is too short, Whitebeet continues to respond with busy `0x01`. If the delay is too long, of course you run the risk of timing out, or colliding with another incoming EV message. 

@jpo-stx: Can you enumerate the conditions that cause Whitebeet to send response code `0x01` back to host? As I said, my sense is that Whitebeet is "Busy" with messages coming thru on EV side, which takes precedence since EV is effectively the "master" and EVSE is "slave". In the case of incoming messages on both EV and EVSE interfaces, it is easier to ignore the EVSE message while parsing new message from EV since new data from EV may make the incoming EVSE data irrelevant. Is this the case? Does Whitebeet always drop EVSE frames when messages are arriving at the same time on both interfaces? Or, does Whitebeet ever buffer incoming EVSE message when new EV message is arriving? Are there other causes of response code `0x01`?

Thanks again for your time,
Zach

**Comment by jpo-stx** [comment]
Hi @zacharyalutz and @IonelFratila let me describe briefly what the Whitebeet is doing internally:

1. Whitebeet receives a message from the EV, i.e. CurrentDemandReq.
2. It decodes this message from EXI to the message buffer.
3. After doing internal checks of the message (message sequence, session ID, etc.) it sends the _Request Charge Loop Parameters_ message to the host.
4. Then it initializes the message buffer to build the response message. This takes a few "ticks".
5. When the buffer is initialized, the Whitebeet is ready to receive the _Set Charge Loop Parameters_ message to directly put the received parameters in the message buffer.
6. The contents of the message buffer are then encoded to EXI and sent to the EV.

Hopefully this helps understanding why the Whitebeet is responsing with the busy response code.

**Comment by IonelFratila** [comment]
Hi @jpo-stx, thank you for the brief explanation of the possible causes of the busy response code. It is no so obvious to me why the WB module is not so busy to send a response with 0x01 code, but is too busy to analyze the content of the command message and to send an OK message instead. I think actually it is a matter of synchronizing two separated processes (one that send the response message to the host and one that analyze the command message and prepare the right answer), but it is only a guess. Anyway, it is no so important to me. After repeating the Set Authorization message several times with different delays, my conclusion is:
- if the delay between the Authorization Request and Set Authorization command is about 2ms, first answer always contains the rezult code 0x01, and the second command receives 0x00 code
- if the delay is set to 25ms, the answer code is 0x00 most of the time (very rarely the message is repeated)
So I will use the 25ms delay for the Set Authorization command (and maybe for others) and (just to be sure) I will repeat the command a maximum of 3 times, until I receive the OK answer.

Now I have other problems:
1.After updating the WB module to V.01_01_04, when I send the Set Schedules command (after receiving the Request schedules message), the message was formatted according to the old version of the WB (in the user manual rev.2.8 Set Schedules command does not contains the TimeAnchor field anymore), so my message was obviously wrong. The problem is that WB send an OK answer to this message and I don't know how the information in this erroneous message will be used.

ETx: FFFFFFFFFFFF 123456789ABC 6003 0004001A C0276B140012 [00000000000000000000010000FFFF003203]00C1
ERx: 123456789ABC C49300215136 6003 00040009 C0276B140001 [00]D5C1	;Set Schedules result=0x00 - OK!!! even if the sent parameters mean nothing, they have wrong values ​​and some of them should not even appear (message length is incorrect).

2.Regarding the Exponential format, can you confirm if the following values are accepted (they are representing the same value):
40.0V = 0x000401
40.0V = 0x002800
40.0V = 0x0190FF
40.0V = 0x0FA0FE
40.0V = 0x9C40FD
Thank You,
Best Regards,
Ionel Fratila

**Comment by jpo-stx** [comment]
Hi @IonelFratila ,

1. Thanks for the hint, I could reproduce the issue and indeed the Whitebeet accepts the frame because it sees a zero for the schedule tuple count and hasn't checked if there is at least one schedule tuple in the message, the check if all data was processed is also skipped in this case. The fix will be included in version V01_01_06 since we have already finalized V01_01_05.
2. The first 4 formats will be accepted and calculate to 40V. The last one would be -25536 * 10^-3 = -25.536V because the value ranges from 32767 to -32768.

BR Jan

**Comment by IonelFratila** [comment]
H @jpo-stx OK, you have right, I forgot that is defined as sint16.
Thank You,
Best Regards,
Ionel

**Comment by IonelFratila** [comment]
Hi @jpo-stx, I have a question regarding the Cable Check sequence.
The sequence is started by the WB module by sending the Request Cable Check Status message (SubID=0x86), followed by a number of Request Cable Check Parameters message (SubID=0x87). During Cable Check execution, the host controller should answer with Set Cable Check Parameters command (SubID=0x6D, that includes present isolation status) to each Request Cable Check Parameters and at the end of the Cable Check execution host controler should send (with respect to Time-Out) a Set Cable Check Status message (SubID=0x6C with Result code=Succeeded). I noticed that all messages sent to the EV contain the EVSEStatusCode=EVSE_Ready and the host controller has no means to change this.
Please tell me what the host controller should send in case of a normal stop or even an Emergency Stop condition, in order to interrupt the Cable Check sequence and send to the EV an EVSEStatusCode=EVSE_Shutdown or EVSE_EmergencyShutdown (or other values, according to the standard). The same problem appears also during PreCharge or Charging sequence.
Thank You,
Best Regards,
Ionel Fratila

**Comment by jpo-stx** [comment]
Hello @IonelFratila ,

in the charge loop you can set the response code to either "3: Stop charging" or "4: Renegotiate", see chapter 17.10.17 Set Charge Loop Parameters.

In Pre Charge and Cable Check you can stop by using the stop command 0x43. This forces a TCP disconnect. Do you have any issues with that in the pre charge and charge loop phase? Does the EV needs the EVSE_Shutdown status code?

BR Jan
